name: Secret CI Trigger

on:
  pull_request:
    # We also want this workflow triggered if the 'Extra CI' label is added
    # or present when PR is updated
    types:
      - synchronize
      - labeled

jobs:
  tests:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'Secret CI')
    steps:
      - name: Run
        run: echo "hello"
